version: "3.9"
services:
  frontend:
    image: docked-dotnet_frontend:latest
    build: ./src/DockedDotnet.Web/
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro   
    ports:
      - 4000:4000
  backend:
    image: docked-dotnet_backend:latest
    build: ./src/DockedDotnet.Api/
    environment:
      ASPNETCORE_ENVIRONMENT: Development
  mongodb:
    image: mongo:latest
    container_name: monogdb
    volumes:
      - ./_database:/data/db